# Generated by Django 4.2 on 2023-05-05 13:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name_course", models.CharField(max_length=50)),
                ("Course_credit", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("majors", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "National_id",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(10),
                        ],
                    ),
                ),
                (
                    "Student_id",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.MaxLengthValidator(8),
                        ],
                    ),
                ),
                ("First_name", models.CharField(max_length=50)),
                ("Last_name", models.CharField(max_length=50)),
                ("Birth_date", models.DateField()),
                ("City_born", models.CharField(max_length=50)),
                ("Date_enterance", models.DateField()),
                ("Units_numbers", models.CharField(max_length=3)),
                ("is_study_now", models.BooleanField(default=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/Students/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "major",
                    models.ManyToManyField(to="product.major", verbose_name="Majors"),
                ),
                ("study_courses", models.ManyToManyField(to="product.courses")),
            ],
        ),
        migrations.CreateModel(
            name="Instructors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "National_id",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(10),
                        ],
                    ),
                ),
                (
                    "Instructor_id",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(9),
                            django.core.validators.MaxLengthValidator(9),
                        ],
                    ),
                ),
                ("First_name", models.CharField(max_length=50)),
                ("Last_name", models.CharField(max_length=50)),
                ("Birth_date", models.DateField(auto_now_add=True)),
                ("City_born", models.CharField(max_length=50)),
                ("Instructor_salary", models.IntegerField()),
                ("is_instructor_now", models.BooleanField(default=True)),
                ("Description_Instructor", models.TextField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/Instructors/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "Instructor_degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.major"
                    ),
                ),
                ("Teach_courses_id", models.ManyToManyField(to="product.courses")),
            ],
        ),
        migrations.AddField(
            model_name="courses",
            name="Major_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.major"
            ),
        ),
    ]
