# Generated by Django 4.2 on 2023-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenttable",
            name="amount",
            field=models.IntegerField(verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="paymenttable",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("Active (Early Bird)", "Active (Early Bird)"),
                    ("Active (Standart)", "Active (Standart)"),
                    ("Active (on site)", "Active (on site)"),
                    ("Student (Early Bird)", "Student (Early Bird)"),
                    ("Student (Standart)", "Student (Standart)"),
                    ("Student (on site)", "Student (on site)"),
                ],
                max_length=50,
                verbose_name="Payment Type",
            ),
        ),
    ]
